### PR TITLE
Up deps, from typings to @types

### PR DESCRIPTION
**Pull request by olegreznichenko**
Hello, may I help you, maybe better use with typescript 2.X @types ?

### CODE REVIEW

**Comment by steveblue** [comment]
This is great work @olegreznichenko I will review this evening and merge in

**Comment by steveblue** [comment]
@olegreznichenko why is the requirejs @types necessary?

**Comment by steveblue** [comment]
This PR also breaks the production build @olegreznichenko

**Comment by olegreznichenko** [comment]
@steveblue, i can try to fix this. What about requirejs @types, if no need in a future i can remove

**Comment by steveblue** [comment]
Hold on @olegreznichenko Im about to release a working build for 2.0.0 release of Angular

**Comment by steveblue** [comment]
OK @olegreznichenko I updated master with a working build that tracks Angular 2.0.0 release. Updating Rollup to 0.35.0 breaks the build, possibly an issue with ngc and a bug in the Angular source.

**Comment by steveblue** [comment]
It would be awesome to have @types working though, no more typings install!

**Comment by olegreznichenko** [comment]
Try it pls)

**Comment by olegreznichenko** [comment]
I update dependencies and angular to 2.0.1, test dev and build - it works fine. Test on your machine.

**Comment by steveblue** [comment]
@olegreznichenko I made the changes locally and pushed to master, thank you for your contribution

**Pull request closed without merging**
